version: "3.8"

services:
  pgdb:
    image: postgres:alpine
    container_name: pgdb_cont
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=runner-iodb
    ports:
      - "5432:5432"
